on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy static website to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2 using SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: "/home/ubuntu/site-files"

      - name: Deploy to NGINX web root
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /home/ubuntu/site-files
            sudo mkdir -p /var/www/html

            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/site-files/* /var/www/html/

            sudo chown -R www-data:www-data /var/www/html
            sudo systemctl restart nginx

